name: Daily Amazon Price Tracker

on:
  schedule:
    - cron: '0 12 * * *'
    - cron: '0 23 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install latest Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tracker script
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        run: python amazon_price.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add amazon_price_tracking.csv
          git commit -m "Update price data: $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push

